spring:
  datasource:
    username: root
    password: ccbysq520
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_platform?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hospital.pojo

server:
  port: 9000